In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
arr=np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# dimention in array

In [11]:
arr=np.array(20)
print(arr)
print(arr.ndim)

20
0


In [12]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [13]:
arr=np.array([[1,2,3],[4.6,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1.  2.  3. ]
 [4.6 5.  6. ]]
<class 'numpy.ndarray'>
2


In [14]:
arr=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[5,6,7]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [5 6 7]]]
3


In [15]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


# indexing

In [16]:
arr=np.array([1,2,3])
print(arr[0])

1


In [17]:
m=np.array([47,5,6,7,8,9,5])
print(m[2])
print(m[0])
print(m[2]+m[1]+m[0])

6
47
58


In [18]:
arr=np.array([[10,30,40,50],[60,70,80,90]])
print(arr[0,1])

30


In [19]:
print(arr[0,0]+arr[0,2])

50


# 3d

In [20]:
arr = np.array([[[10,30,40,50],[3,4,5,6]],[[3,4,5,6],[6,7,8,9]]])
print(arr)

[[[10 30 40 50]
  [ 3  4  5  6]]

 [[ 3  4  5  6]
  [ 6  7  8  9]]]


# slicing



In [21]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1:5])

[2 3 4 5]


In [22]:
print(arr[::2])

[1 3 5]


In [23]:
arr=np.array([[10,30,40],[40,50,6]])
print(arr[1,[1:2]])

SyntaxError: invalid syntax (3402700636.py, line 2)

# checking the data type of an aaray

In [ ]:
arr=np.array([1,2,3,4])
print(arr.dtype)

In [ ]:
arr=np.array(['animals','bat','cat'])
print(arr.dtype)

# creating aeeays with defined data type

In [ ]:
arr=np.array([1,2,3,4],dtype="S")
print(arr.dtype)

# numpy array shape

In [ ]:
arr=np.array([[1,2,3],[5,6,7]])
print(arr.shape)

In [ ]:
arr=np.array([[[1,2,3],[5,6,7],[5,6,7]]])
print(arr.shape)

# joining numpy arrays

In [ ]:
arr1 = np.array([1,2,3])
arr2=  np.array([4,5,6])
arr=np.concatenate ((arr1,arr2))
print(arr)

In [ ]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

In [ ]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

# splitting 

In [ ]:
arr1=np.array([1,2,3,4,5,6])
new=np.array_split(arr,3)
print(new)

In [ ]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(np.array_split(arr1,4))

# ravel & flaten

In [ ]:
import numpy as np
m=np.array([[1,2,3],[5,6,7]])
n=m.ravel()
print(n)

In [ ]:
c=np.array([[[[1,2,3,4],[2,3,4,5],[5,6,7,8]]]])
d=c.ravel()
print(d)
print(d.ndim)

# unique function

In [ ]:
k=np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
z=np.unique(k)
print(z)

In [ ]:
k=np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
z=np.unique(k,return_index=True)
print(z)

# delete

In [ ]:
a=np.array([1,2,3,4,5])
d=np.delete(a,[1])
print(d)

In [ ]:
x=np.array(([2,3,4,5],[4,5,6,7]))
print(x)
m=np.delete(x,1,axis=0)
print(m)